version: '3.8'

services:

  db:
    image: mysql:latest
    container_name: security_bank
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_DATABASE=security_bank
      - MYSQL_USER=root
      - MYSQL_PASSWORD=strong_password
      - MYSQL_ROOT_PASSWORD=strong_password
    ports:
      - "3306:3306"